// data.jsx — sample data for DigiPicks prototype
// All fictional. Realistic but not real creators / events.

const CREATORS = [
  {
    id: 'sharpedge',
    handle: '@sharpedgebets',
    name: 'SharpEdge Bets',
    avatar: { color: '#1F8A5B', mono: 'SE' },
    verified: true,
    niche: 'NFL Sides & Totals',
    sports: ['NFL'],
    bio: 'Former NFL analytics consultant. Sides + totals only. Closing line value tracked publicly since 2022.',
    subs: 1284,
    startingPrice: 39,
    winRate: 0.611,
    record: '47-30-3',
    last10: 'WWLWWLWWWL',
    units: '+38.4u',
    streak: 'W3',
    tags: ['Sides', 'Totals', 'CLV-tracked'],
    trending: true,
  },
  {
    id: 'nordic',
    handle: '@nordicpicks',
    name: 'Nordic Picks',
    avatar: { color: '#3A4F7A', mono: 'NP' },
    verified: true,
    niche: 'Soccer & Tennis Props',
    sports: ['Soccer', 'Tennis'],
    bio: 'EPL, Bundesliga, ATP/WTA props. Disciplined unit sizing. No parlays.',
    subs: 612,
    startingPrice: 25,
    winRate: 0.586,
    record: '92-65-8',
    last10: 'WWWLWLWWLW',
    units: '+21.2u',
    streak: 'W2',
    tags: ['Props', 'Soccer', 'Tennis'],
    trending: true,
  },
  {
    id: 'courtvision',
    handle: '@courtvisionpro',
    name: 'CourtVision Pro',
    avatar: { color: '#7A3A8E', mono: 'CV' },
    verified: true,
    niche: 'NBA Player Props',
    sports: ['NBA'],
    bio: 'Player props specialist. Pace and matchup-driven. Pre-game only, no live bets.',
    subs: 2104,
    startingPrice: 49,
    winRate: 0.628,
    record: '156-92-5',
    last10: 'WWLWWWLWWW',
    units: '+62.7u',
    streak: 'W4',
    tags: ['Player Props', 'NBA', 'Pre-game'],
    trending: true,
  },
  {
    id: 'goalline',
    handle: '@goallineinsider',
    name: 'GoalLine Insider',
    avatar: { color: '#8E5A3A', mono: 'GL' },
    verified: true,
    niche: 'NFL Props & Anytime TDs',
    sports: ['NFL'],
    bio: 'Anytime TD specialist. Receiving yardage and rushing props. Discipline > volume.',
    subs: 880,
    startingPrice: 35,
    winRate: 0.564,
    record: '110-85-2',
    last10: 'LWWLWWWLWL',
    units: '+14.1u',
    streak: 'L1',
    tags: ['Props', 'NFL', 'TDs'],
  },
  {
    id: 'icesharp',
    handle: '@icesharp',
    name: 'IceSharp NHL',
    avatar: { color: '#3A6E8E', mono: 'IS' },
    verified: true,
    niche: 'NHL Sides, SOG, Goalies',
    sports: ['NHL'],
    bio: 'NHL only. Goalie matchups, shots-on-goal props, puck line value.',
    subs: 421,
    startingPrice: 19,
    winRate: 0.598,
    record: '74-50-3',
    last10: 'WLWWWLWLWW',
    units: '+22.0u',
    streak: 'W1',
    tags: ['NHL', 'Goalies', 'Props'],
  },
  {
    id: 'proplab',
    handle: '@proplab',
    name: 'PropLab',
    avatar: { color: '#5B7A3A', mono: 'PL' },
    verified: false,
    niche: 'Cross-sport Player Props',
    sports: ['NBA', 'NFL', 'MLB'],
    bio: 'Multi-sport prop research. Model-driven. Newer but transparent log.',
    subs: 142,
    startingPrice: 15,
    winRate: 0.553,
    record: '38-31-1',
    last10: 'LWWLWWWLLW',
    units: '+6.8u',
    streak: 'W1',
    tags: ['Props', 'Model'],
    trending: false,
  },
];

const SPORTS = ['NFL','NBA','NHL','MLB','Soccer','Tennis','UFC'];

const EVENTS_TODAY = [
  { id:'ev1', sport:'NBA', league:'NBA', home:'Lakers', away:'Nuggets', time:'7:30 PM ET', creators:8, picks:14, featured:true },
  { id:'ev2', sport:'NBA', league:'NBA', home:'Celtics', away:'Knicks', time:'8:00 PM ET', creators:6, picks:11 },
  { id:'ev3', sport:'NHL', league:'NHL', home:'Rangers', away:'Bruins', time:'7:00 PM ET', creators:4, picks:7 },
  { id:'ev4', sport:'NHL', league:'NHL', home:'Maple Leafs', away:'Panthers', time:'7:30 PM ET', creators:3, picks:5 },
  { id:'ev5', sport:'Soccer', league:'EPL', home:'Arsenal', away:'Man City', time:'3:30 PM ET', creators:5, picks:9, featured:true },
  { id:'ev6', sport:'Soccer', league:'Bundesliga', home:'Leverkusen', away:'Dortmund', time:'12:30 PM ET', creators:3, picks:5 },
  { id:'ev7', sport:'Tennis', league:'ATP Madrid', home:'Alcaraz', away:'Sinner', time:'2:00 PM ET', creators:4, picks:6 },
  { id:'ev8', sport:'NFL', league:'NFL Draft', home:'Round 1', away:'', time:'8:00 PM ET', creators:2, picks:3 },
];

const FEED_PICKS = [
  {
    id:'p1', creator:'courtvision', access:'premium',
    sport:'NBA', league:'NBA',
    event:'Lakers vs Nuggets', eventTime:'Tonight 7:30 PM ET',
    title:'Lakers 1H Total — Over 112.5',
    market:'1H Over/Under', selection:'Over 112.5', odds:'-110',
    units:'2.5u', confidence:'High',
    posted:'42m ago', status:'pending',
    teaser:'Both teams hovering 53–55% pace tier in last 5 games against quality defenses; Denver coming off back-to-back…',
  },
  {
    id:'p2', creator:'sharpedge', access:'free',
    sport:'NFL', league:'NFL',
    event:'NFL Draft Night One', eventTime:'Tonight 8:00 PM ET',
    title:'Chargers Position — Defense (First Pick)',
    market:'Draft Prop', selection:'Defense', odds:'+135',
    units:'1u', confidence:'Medium',
    posted:'2h ago', status:'pending',
    body:'Big board reads pulled from three insider sources cross-referenced with team needs. Chargers DC hire signals…',
  },
  {
    id:'p3', creator:'nordic', access:'premium',
    sport:'Soccer', league:'EPL',
    event:'Arsenal vs Man City', eventTime:'Today 3:30 PM ET',
    title:'Saka Anytime Goal Scorer',
    market:'Player Goalscorer', selection:'Saka Anytime', odds:'+165',
    units:'1.5u', confidence:'Medium',
    posted:'5h ago', status:'pending',
    teaser:'City fullback rotation suggests Akanji at LB, Saka has scored in 4 of his last 5 vs City…',
  },
  {
    id:'p4', creator:'icesharp', access:'free',
    sport:'NHL', league:'NHL',
    event:'Rangers vs Bruins', eventTime:'Tonight 7:00 PM ET',
    title:'Shesterkin Saves Over 28.5',
    market:'Goalie Saves O/U', selection:'Over 28.5', odds:'-115',
    units:'2u', confidence:'High',
    posted:'1h ago', status:'pending',
    body:'Boston averaging 32.4 SOG/60 over last 8 games. Shesterkin matchup spreads well above prop line in tracked sample.',
  },
  {
    id:'p5', creator:'goalline', access:'premium',
    sport:'NFL', league:'NFL',
    event:'Reagan Bowl Replay (Practice)', eventTime:'Tomorrow',
    title:'Mahomes Passing Yards — Over 274.5',
    market:'Player Passing Yards', selection:'Over 274.5', odds:'-105',
    units:'1.5u', confidence:'High',
    posted:'8h ago', status:'pending',
    teaser:'Defensive scheme they\'ll face has surrendered 290+ in 7 of last 9 to top-12 QBs…',
  },
];

const RECENT_RESULTS = [
  { id:'r1', creator:'courtvision', title:'Jokic Triple Double — Yes', odds:'+220', units:'1u', result:'win', netUnits:'+2.20', date:'Yesterday', sport:'NBA' },
  { id:'r2', creator:'sharpedge', title:'Bills -3.5 vs Dolphins', odds:'-110', units:'2u', result:'win', netUnits:'+1.82', date:'Yesterday', sport:'NFL' },
  { id:'r3', creator:'nordic', title:'Liverpool/Chelsea — Both Teams Score', odds:'-140', units:'1u', result:'loss', netUnits:'-1.00', date:'2d ago', sport:'Soccer' },
  { id:'r4', creator:'icesharp', title:'Hellebuyck Saves Over 26.5', odds:'-105', units:'1u', result:'win', netUnits:'+0.95', date:'2d ago', sport:'NHL' },
  { id:'r5', creator:'courtvision', title:'Tatum Points Over 27.5', odds:'-115', units:'1u', result:'loss', netUnits:'-1.00', date:'3d ago', sport:'NBA' },
  { id:'r6', creator:'sharpedge', title:'Chiefs/Ravens 1Q Under 10.5', odds:'-120', units:'1u', result:'push', netUnits:'0.00', date:'3d ago', sport:'NFL' },
  { id:'r7', creator:'goalline', title:'Hill Receptions Over 5.5', odds:'-105', units:'1u', result:'win', netUnits:'+0.95', date:'4d ago', sport:'NFL' },
  { id:'r8', creator:'proplab', title:'Curry 3PM Over 4.5', odds:'+105', units:'1u', result:'loss', netUnits:'-1.00', date:'4d ago', sport:'NBA' },
];

const APPLICATIONS = [
  { id:'a1', name:'Marco Diaz', handle:'@marco_diaz', sport:'MLB', niche:'MLB Run Lines + Totals', subs:'~3,200 (X+Discord)', priceHint:'$25/mo', proof:3, submitted:'2h ago', status:'review', winClaim:'56% over 2y' },
  { id:'a2', name:'Lena Park', handle:'@lenapark', sport:'WNBA', niche:'WNBA Player Props', subs:'~890 (Discord)', priceHint:'$15/mo', proof:5, submitted:'5h ago', status:'review', winClaim:'63% YTD' },
  { id:'a3', name:'Trevor Hill', handle:'@hill_picks', sport:'UFC', niche:'UFC Method/Round', subs:'~1,400 (X)', priceHint:'$35/mo', proof:2, submitted:'1d ago', status:'more_info', winClaim:'58% career' },
  { id:'a4', name:'Aiyana Cross', handle:'@cross_courts', sport:'Tennis', niche:'ATP/WTA Game Spreads', subs:'~410 (Telegram)', priceHint:'$19/mo', proof:6, submitted:'1d ago', status:'flagged', winClaim:'71% (disputed)' },
  { id:'a5', name:'Jamie Liu', handle:'@jamie_models', sport:'Multi', niche:'Model-driven props', subs:'~6,200 (Substack)', priceHint:'$49/mo', proof:8, submitted:'2d ago', status:'review', winClaim:'59.4% verified' },
];

const POSTS_MANAGER = [
  { id:'pm1', title:'Lakers 1H Total — Over 112.5', event:'LAL @ DEN', access:'premium', status:'published', pubDate:'Today, 6:48 PM', views:1284, saves:312, grade:'pending' },
  { id:'pm2', title:'Tatum Points Over 27.5', event:'BOS @ PHI', access:'premium', status:'published', pubDate:'Yesterday', views:2018, saves:402, grade:'loss' },
  { id:'pm3', title:'Jokic Triple Double — Yes', event:'DEN @ MIN', access:'premium', status:'published', pubDate:'2d ago', views:1842, saves:489, grade:'win' },
  { id:'pm4', title:'Pre-Sunday Slate Notes', event:'NFL Slate', access:'free', status:'published', pubDate:'3d ago', views:5402, saves:182, grade:null },
  { id:'pm5', title:'Suns vs Wolves — Live Take', event:'PHX @ MIN', access:'premium', status:'draft', pubDate:'—', views:0, saves:0, grade:null },
  { id:'pm6', title:'Saturday Slate VIP Bundle', event:'Multi', access:'vip', status:'scheduled', pubDate:'Sat, 11:30 AM', views:0, saves:0, grade:null },
];

const SUBSCRIBERS = [
  { id:'s1', name:'Alex Morgan', plan:'Premium', status:'active', start:'Jan 14', renew:'Jun 14', ltv:'$294', engagement:0.82, vip:false },
  { id:'s2', name:'Diego Romero', plan:'VIP', status:'active', start:'Mar 02', renew:'Jun 02', ltv:'$396', engagement:0.94, vip:true },
  { id:'s3', name:'Priya Anand', plan:'Premium', status:'past_due', start:'Feb 21', renew:'May 21', ltv:'$147', engagement:0.61, vip:false },
  { id:'s4', name:'Sam Whitlock', plan:'Premium', status:'active', start:'Apr 09', renew:'Jun 09', ltv:'$78', engagement:0.45, vip:false },
  { id:'s5', name:'Riley Chen', plan:'VIP', status:'active', start:'Dec 02', renew:'Jun 02', ltv:'$594', engagement:0.91, vip:true },
  { id:'s6', name:'Dana Quintero', plan:'Free Follow', status:'active', start:'Apr 28', renew:'—', ltv:'$0', engagement:0.31, vip:false },
  { id:'s7', name:'Marcus Webb', plan:'Premium', status:'cancelled', start:'Feb 03', renew:'Ends May 18', ltv:'$117', engagement:0.55, vip:false },
];

const NOTIFICATIONS = [
  { id:'n1', kind:'pick', title:'CourtVision Pro posted a new Premium pick', sub:'Lakers 1H Total — Over 112.5 · Tonight 7:30 PM ET', time:'42m', unread:true },
  { id:'n2', kind:'grade', title:'Bills -3.5 graded as Win', sub:'+1.82u net · SharpEdge Bets', time:'1h', unread:true },
  { id:'n3', kind:'creator', title:'Nordic Picks went live with EPL slate notes', sub:'Free preview attached', time:'3h', unread:false },
  { id:'n4', kind:'billing', title:'Subscription renews in 3 days', sub:'CourtVision Pro Premium · $49.00', time:'5h', unread:false },
  { id:'n5', kind:'platform', title:'Responsible-betting limits updated', sub:'Review your weekly cap in Settings', time:'1d', unread:false },
];

window.DATA = {
  CREATORS, SPORTS, EVENTS_TODAY, FEED_PICKS, RECENT_RESULTS,
  APPLICATIONS, POSTS_MANAGER, SUBSCRIBERS, NOTIFICATIONS,
};
window.creatorById = (id) => CREATORS.find(c => c.id === id);
